### PR TITLE
Added PartiQL NodeJS example

### PR DESCRIPTION
**Pull request by zachjonesnoel**
*Description of changes:*
1. Added batchExecuteStatement with PartiQL NodeJS example.
2. Added reference to examples on ReadMe.
3. Rectified some broken links on ReadMe.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by NoSQLKnowHow** [comment]
Hey. In the batch-execute-statement with the statement with the values like that, is there any possibility of a SQL injection with that style?

**Comment by zachjonesnoel** [comment]
Hey @NoSQLKnowHow , yea SQL injection is possible.

**Comment by NoSQLKnowHow** [comment]
How can this be rewritten to now have that as possible?

**Comment by zachjonesnoel** [comment]
Sure @NoSQLKnowHow I will put up a sample for the same with SQL injection and the one to restrict SQL injection.

**Pull request merged**
